name: Deploy automático para Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 82.25.67.216
          username: u698920850.appuniasessor
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          
          # envia tudo
          local-dir: ./
          # para dentro da pasta pública da Hostinger
          server-dir: /public_html/
